### ISSUE TITLE
不建议将Jar包放到代码仓库，会严重增加git仓库的空间占用

### ISSUE THREAD

**Issue by zhangsean** [mrhuo/database2api#9]
每次发布的时候把jar作为附件上传到发布详情即可，这也是大部分项目的做法。

**Comment by mrhuo** [comment]
大佬，你说得对，下次就改~~ 👍👍👍

**Comment by mrhuo** [comment]
已按照大佬的建议修改，已删除jar文件

**Comment by zhangsean** [comment]
纯技术讨论：目前直接下载源代码zip压缩包已经很小了，但通过git clone全新克隆到空目录还是很大，因为代码仓库曾经提交了二进制的jar，.git目录里就要保存这个二进制文件，以便可以通过git checkout回到曾经有jar的那个历史提交代码状态。
这也是为什么git仓库不建议提交二进制文件，这个文件每次修改，.git目录就要保存这个完整的二进制文件，所以整个仓库提交会持续累加。
所以这种误将非常大的二进制文件提交到git仓库的情况，只git del是不能完全清理的。
最直接的清理办法就是重建git仓库，当然会丢失目前所有的提交记录。
目前这样已经可以了，没必要再重建仓库了。毕竟很少人会去git clone仓库到本地，真正的开发者也不关心下载了多久（ps.就算关心也只能等哈哈）

**Comment by zhangsean** [comment]
如图：`git clone` 下来仓库有126M，.git目录就有125M，其实源代码就1M左右。
![image](https://github.com/user-attachments/assets/1fcc54a1-d360-4574-b2e2-a5a7e39c87dc)

**Comment by mrhuo** [comment]
👍学到了，我还没注意过这个文件夹的大小。受益匪浅。

**Comment by shoot82003** [comment]
你把database2api.jar删除后,要如何构建database2api.jar
